//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xbox.Live.Phone.Services.Xbox.Live.Phone.Services.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xbox.Live.Phone.Services.Xbox.Live.Phone.Services.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        internal static string ClosetReadColor {
            get {
                return ResourceManager.GetString("ClosetReadColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen on {0}..
        /// </summary>
        internal static string LastSeen_Date {
            get {
                return ResourceManager.GetString("LastSeen_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen {0} hours ago..
        /// </summary>
        internal static string LastSeen_Hour {
            get {
                return ResourceManager.GetString("LastSeen_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen 1 hour ago..
        /// </summary>
        internal static string LastSeen_Hour_Singular {
            get {
                return ResourceManager.GetString("LastSeen_Hour_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen less than 1 minute ago..
        /// </summary>
        internal static string LastSeen_LessThanOneMinute {
            get {
                return ResourceManager.GetString("LastSeen_LessThanOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen {0} minutes ago..
        /// </summary>
        internal static string LastSeen_Minute {
            get {
                return ResourceManager.GetString("LastSeen_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen 1 minute ago..
        /// </summary>
        internal static string LastSeen_Minute_Singular {
            get {
                return ResourceManager.GetString("LastSeen_Minute_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen on {0} playing {1}..
        /// </summary>
        internal static string LastSeenPlaying_Date {
            get {
                return ResourceManager.GetString("LastSeenPlaying_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen {0} hours ago playing {1}..
        /// </summary>
        internal static string LastSeenPlaying_Hour {
            get {
                return ResourceManager.GetString("LastSeenPlaying_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen 1 hour ago playing {0}..
        /// </summary>
        internal static string LastSeenPlaying_Hour_Singular {
            get {
                return ResourceManager.GetString("LastSeenPlaying_Hour_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen less than 1 minute ago playing {0}..
        /// </summary>
        internal static string LastSeenPlaying_LessThanOneMinute {
            get {
                return ResourceManager.GetString("LastSeenPlaying_LessThanOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen {0} minutes ago playing {1}..
        /// </summary>
        internal static string LastSeenPlaying_Minute {
            get {
                return ResourceManager.GetString("LastSeenPlaying_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen 1 minute ago playing {0}..
        /// </summary>
        internal static string LastSeenPlaying_Minute_Singular {
            get {
                return ResourceManager.GetString("LastSeenPlaying_Minute_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent you a picture.
        /// </summary>
        internal static string Message_Subject_EmptySubjectWithImage {
            get {
                return ResourceManager.GetString("Message_Subject_EmptySubjectWithImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent you a voice message.
        /// </summary>
        internal static string Message_Subject_EmptySubjectWithVoice {
            get {
                return ResourceManager.GetString("Message_Subject_EmptySubjectWithVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subject.
        /// </summary>
        internal static string Message_Summary_EmptySubject {
            get {
                return ResourceManager.GetString("Message_Summary_EmptySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited you.
        /// </summary>
        internal static string Message_Summary_GameInvite {
            get {
                return ResourceManager.GetString("Message_Summary_GameInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited you to an Xbox LIVE party.
        /// </summary>
        internal static string Message_Summary_PartyInvite {
            get {
                return ResourceManager.GetString("Message_Summary_PartyInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited you to a voice chat.
        /// </summary>
        internal static string Message_Summary_QuickChatInvite {
            get {
                return ResourceManager.GetString("Message_Summary_QuickChatInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited you to a video chat.
        /// </summary>
        internal static string Message_Summary_VideoChatInvite {
            get {
                return ResourceManager.GetString("Message_Summary_VideoChatInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent you a video message.
        /// </summary>
        internal static string Message_Summary_VideoMessage {
            get {
                return ResourceManager.GetString("Message_Summary_VideoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing {0}.
        /// </summary>
        internal static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
    }
}
