//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRC.Resource.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LRC.Resource.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}.
        /// </summary>
        internal static string AchievementGamerScoreProgressFormat {
            get {
                return ResourceManager.GetString("AchievementGamerScoreProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked {0}.
        /// </summary>
        internal static string Achievements_DateEarned {
            get {
                return ResourceManager.GetString("Achievements_DateEarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t view your achievements..
        /// </summary>
        internal static string Achievements_ErrorToShowInPlaceOfList {
            get {
                return ResourceManager.GetString("Achievements_ErrorToShowInPlaceOfList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        internal static string Achievements_GamerscoreText {
            get {
                return ResourceManager.GetString("Achievements_GamerscoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No achievements..
        /// </summary>
        internal static string Achievements_NoAchievementsText {
            get {
                return ResourceManager.GetString("Achievements_NoAchievementsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        internal static string Achievements_ProgressText {
            get {
                return ResourceManager.GetString("Achievements_ProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue playing to unlock this secret achievement..
        /// </summary>
        internal static string Achievements_SecretDescription {
            get {
                return ResourceManager.GetString("Achievements_SecretDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        internal static string Achievements_SecretGamerscore {
            get {
                return ResourceManager.GetString("Achievements_SecretGamerscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret.
        /// </summary>
        internal static string Achievements_SecretTitle {
            get {
                return ResourceManager.GetString("Achievements_SecretTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to achievements.
        /// </summary>
        internal static string AchievementsHeader {
            get {
                return ResourceManager.GetString("AchievementsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cast.
        /// </summary>
        internal static string Actor_Header {
            get {
                return ResourceManager.GetString("Actor_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cast.
        /// </summary>
        internal static string Actors_Header {
            get {
                return ResourceManager.GetString("Actors_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. {1}.
        /// </summary>
        internal static string Album_DisplayedTrackName {
            get {
                return ResourceManager.GetString("Album_DisplayedTrackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reviews.
        /// </summary>
        internal static string AlbumDetails_Review_Title {
            get {
                return ResourceManager.GetString("AlbumDetails_Review_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overview.
        /// </summary>
        internal static string AlbumDetails_Song_Title {
            get {
                return ResourceManager.GetString("AlbumDetails_Song_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to songs.
        /// </summary>
        internal static string AlbumSongs_Title {
            get {
                return ResourceManager.GetString("AlbumSongs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.
        /// </summary>
        internal static string Artist_Header {
            get {
                return ResourceManager.GetString("Artist_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Beacon_CommentLabel {
            get {
                return ResourceManager.GetString("Beacon_CommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        internal static string Beacon_EditBeaconButtonText {
            get {
                return ResourceManager.GetString("Beacon_EditBeaconButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update beacon.
        /// </summary>
        internal static string Beacon_EditBeaconHeader {
            get {
                return ResourceManager.GetString("Beacon_EditBeaconHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} friends playing now.
        /// </summary>
        internal static string Beacon_FriendsPlayingNow {
            get {
                return ResourceManager.GetString("Beacon_FriendsPlayingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} friends with beacons.
        /// </summary>
        internal static string Beacon_FriendsWithBeacons {
            get {
                return ResourceManager.GetString("Beacon_FriendsWithBeacons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 friend playing now.
        /// </summary>
        internal static string Beacon_OneFriendPlayingNow {
            get {
                return ResourceManager.GetString("Beacon_OneFriendPlayingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 friend with a beacon.
        /// </summary>
        internal static string Beacon_OneFriendWithBeacon {
            get {
                return ResourceManager.GetString("Beacon_OneFriendWithBeacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        internal static string Beacon_RemoveBeaconButtonText {
            get {
                return ResourceManager.GetString("Beacon_RemoveBeaconButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set.
        /// </summary>
        internal static string Beacon_SetBeaconButtonText {
            get {
                return ResourceManager.GetString("Beacon_SetBeaconButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set beacon.
        /// </summary>
        internal static string Beacon_SetBeaconHeader {
            get {
                return ResourceManager.GetString("Beacon_SetBeaconHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add comment. You&apos;re currently suspended from communications..
        /// </summary>
        internal static string Beacon_UserBannedCommentBoxText {
            get {
                return ResourceManager.GetString("Beacon_UserBannedCommentBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bio.
        /// </summary>
        internal static string Bio_Header {
            get {
                return ResourceManager.GetString("Bio_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting on console....
        /// </summary>
        internal static string BusyIndicator_LaunchingText {
            get {
                return ResourceManager.GetString("BusyIndicator_LaunchingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string BusyIndicator_LoadingText {
            get {
                return ResourceManager.GetString("BusyIndicator_LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string Cancel_Text {
            get {
                return ResourceManager.GetString("Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cast and crew.
        /// </summary>
        internal static string CastAndCrew_Header {
            get {
                return ResourceManager.GetString("CastAndCrew_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string ConnectedMessage {
            get {
                return ResourceManager.GetString("ConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string ConnectingMessage {
            get {
                return ResourceManager.GetString("ConnectingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explicit.
        /// </summary>
        internal static string Content_Explicit {
            get {
                return ResourceManager.GetString("Content_Explicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue without Wi-Fi.
        /// </summary>
        internal static string ContinueWithoutWifi {
            get {
                return ResourceManager.GetString("ContinueWithoutWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string Description_Header {
            get {
                return ResourceManager.GetString("Description_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to director.
        /// </summary>
        internal static string Director_Header {
            get {
                return ResourceManager.GetString("Director_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directors.
        /// </summary>
        internal static string Directors_Header {
            get {
                return ResourceManager.GetString("Directors_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to albums.
        /// </summary>
        internal static string Discography_Header {
            get {
                return ResourceManager.GetString("Discography_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums are currently unavailable..
        /// </summary>
        internal static string Discography_NotFound {
            get {
                return ResourceManager.GetString("Discography_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min.
        /// </summary>
        internal static string DurationInMinutes {
            get {
                return ResourceManager.GetString("DurationInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code:.
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Fatal_Title {
            get {
                return ResourceManager.GetString("Fatal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;.
        /// </summary>
        internal static string Friend_BeaconText {
            get {
                return ResourceManager.GetString("Friend_BeaconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beacon set.
        /// </summary>
        internal static string Friend_DefaultBeaconText {
            get {
                return ResourceManager.GetString("Friend_DefaultBeaconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played {0} Days Ago.
        /// </summary>
        internal static string Friend_PlayedDaysAgoText {
            get {
                return ResourceManager.GetString("Friend_PlayedDaysAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played {0} Hours Ago.
        /// </summary>
        internal static string Friend_PlayedHoursAgoText {
            get {
                return ResourceManager.GetString("Friend_PlayedHoursAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played {0} Minutes Ago.
        /// </summary>
        internal static string Friend_PlayedMinutesAgoText {
            get {
                return ResourceManager.GetString("Friend_PlayedMinutesAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played {0} Months Ago.
        /// </summary>
        internal static string Friend_PlayedMonthsAgoText {
            get {
                return ResourceManager.GetString("Friend_PlayedMonthsAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played Yesterday.
        /// </summary>
        internal static string Friend_PlayedOneDayAgoText {
            get {
                return ResourceManager.GetString("Friend_PlayedOneDayAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played 1 Hour Ago.
        /// </summary>
        internal static string Friend_PlayedOneHourAgoText {
            get {
                return ResourceManager.GetString("Friend_PlayedOneHourAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played 1 Minute Ago.
        /// </summary>
        internal static string Friend_PlayedOneMinuteAgoText {
            get {
                return ResourceManager.GetString("Friend_PlayedOneMinuteAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played 1 Month Ago.
        /// </summary>
        internal static string Friend_PlayedOneMonthAgoText {
            get {
                return ResourceManager.GetString("Friend_PlayedOneMonthAgoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing Now.
        /// </summary>
        internal static string Friend_PlayingNowText {
            get {
                return ResourceManager.GetString("Friend_PlayingNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friend activity.
        /// </summary>
        internal static string Friends_FriendActivityText {
            get {
                return ResourceManager.GetString("Friends_FriendActivityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No friend activity..
        /// </summary>
        internal static string Friends_NoFriendsText {
            get {
                return ResourceManager.GetString("Friends_NoFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        internal static string FriendsHeader {
            get {
                return ResourceManager.GetString("FriendsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set or update beacon.
        /// </summary>
        internal static string GameDetails_SetBeaconText {
            get {
                return ResourceManager.GetString("GameDetails_SetBeaconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox Companion.
        /// </summary>
        internal static string Home_Panorama_Title {
            get {
                return ResourceManager.GetString("Home_Panorama_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you begin:.
        /// </summary>
        internal static string HowToConnect_BulletHeader {
            get {
                return ResourceManager.GetString("HowToConnect_BulletHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your console is on and you&apos;re signed in to Xbox LIVE..
        /// </summary>
        internal static string HowToConnect_BulletText1 {
            get {
                return ResourceManager.GetString("HowToConnect_BulletText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On your console, set Xbox Companion to Available in Settings, System, Console Settings..
        /// </summary>
        internal static string HowToConnect_BulletText2 {
            get {
                return ResourceManager.GetString("HowToConnect_BulletText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string HowToConnect_ContinueButtonText {
            get {
                return ResourceManager.GetString("HowToConnect_ContinueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Xbox Companion.
        /// </summary>
        internal static string HowToConnect_Header {
            get {
                return ResourceManager.GetString("HowToConnect_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox Companion lets you use your Windows Phone to connect and play content on your console..
        /// </summary>
        internal static string HowToConnect_InformationalText1 {
            get {
                return ResourceManager.GetString("HowToConnect_InformationalText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images.
        /// </summary>
        internal static string Images_Header {
            get {
                return ResourceManager.GetString("Images_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will exit the current session on your console. Continue?.
        /// </summary>
        internal static string Launch_DifferentTitle_Warning_Message {
            get {
                return ResourceManager.GetString("Launch_DifferentTitle_Warning_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboards are currently unavailable for this game..
        /// </summary>
        internal static string Leaderboards_NoLeaderboardDataText {
            get {
                return ResourceManager.GetString("Leaderboards_NoLeaderboardDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leaderboards.
        /// </summary>
        internal static string LeaderboardsHeader {
            get {
                return ResourceManager.GetString("LeaderboardsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for your Xbox 360 console.
        /// </summary>
        internal static string LookForXboxPage_ConnectingHeader {
            get {
                return ResourceManager.GetString("LookForXboxPage_ConnectingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your console is on and Xbox Companion is set to Available in Settings, System, Console Settings.
        ///
        ///For more info, visit
        ///http://support.xbox.com.
        /// </summary>
        internal static string LookForXboxPage_Error_CanNotConnect {
            get {
                return ResourceManager.GetString("LookForXboxPage_Error_CanNotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you&apos;re signed into Xbox LIVE on both the console and your Windows Phone.
        ///
        ///To enable Xbox Companion on your console, go to Settings, System, Console Settings, Xbox Companion.
        ///
        ///For more info, visit
        ///http://support.xbox.com.
        /// </summary>
        internal static string LookForXboxPage_Error_CanNotFind {
            get {
                return ResourceManager.GetString("LookForXboxPage_Error_CanNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to Xbox LIVE. Make sure your Windows Phone is connected to the Internet.
        ///
        ///For more info, visit
        ///http://support.xbox.com.
        /// </summary>
        internal static string LookForXboxPage_Error_CanNotSignIn {
            get {
                return ResourceManager.GetString("LookForXboxPage_Error_CanNotSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 4 devices can connect to your console at a time. Disconnect a device and try again.
        ///
        ///For more info, visit
        ///http://support.xbox.com.
        /// </summary>
        internal static string LookForXboxPage_Error_TooManyClients {
            get {
                return ResourceManager.GetString("LookForXboxPage_Error_TooManyClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to your console.
        /// </summary>
        internal static string LookForXboxPage_ErrorHeader_CanNotConnect {
            get {
                return ResourceManager.GetString("LookForXboxPage_ErrorHeader_CanNotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find your console.
        /// </summary>
        internal static string LookForXboxPage_ErrorHeader_CanNotFind {
            get {
                return ResourceManager.GetString("LookForXboxPage_ErrorHeader_CanNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t sign in to Xbox LIVE.
        /// </summary>
        internal static string LookForXboxPage_ErrorHeader_CanNotSignIn {
            get {
                return ResourceManager.GetString("LookForXboxPage_ErrorHeader_CanNotSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many devices.
        /// </summary>
        internal static string LookForXboxPage_ErrorHeader_DeviceLimitReached {
            get {
                return ResourceManager.GetString("LookForXboxPage_ErrorHeader_DeviceLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your console is on and Xbox Companion is set to Available in Settings, System, Console Settings..
        /// </summary>
        internal static string LookForXboxPage_Information {
            get {
                return ResourceManager.GetString("LookForXboxPage_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string LookForXboxPage_RetryButtonText {
            get {
                return ResourceManager.GetString("LookForXboxPage_RetryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not allowed.
        /// </summary>
        internal static string LRC_Error_Code_ActionNotAllowed {
            get {
                return ResourceManager.GetString("LRC_Error_Code_ActionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LRC_Error_Code_CriticalFailure {
            get {
                return ResourceManager.GetString("LRC_Error_Code_CriticalFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t sign in..
        /// </summary>
        internal static string LRC_Error_Code_FailedToAuthenticate {
            get {
                return ResourceManager.GetString("LRC_Error_Code_FailedToAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to your console..
        /// </summary>
        internal static string LRC_Error_Code_FailedToConnectToConsole {
            get {
                return ResourceManager.GetString("LRC_Error_Code_FailedToConnectToConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, couldn&apos;t remove your beacon. Try again later..
        /// </summary>
        internal static string LRC_Error_Code_FailedToDeleteBeacon {
            get {
                return ResourceManager.GetString("LRC_Error_Code_FailedToDeleteBeacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get these achievements. Try again..
        /// </summary>
        internal static string LRC_Error_Code_FailedToGetAchievements {
            get {
                return ResourceManager.GetString("LRC_Error_Code_FailedToGetAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get your friends list. Try again..
        /// </summary>
        internal static string LRC_Error_Code_FailedToGetFriendList {
            get {
                return ResourceManager.GetString("LRC_Error_Code_FailedToGetFriendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t retrieve this profile. Try again..
        /// </summary>
        internal static string LRC_Error_Code_FailedToGetUserProfile {
            get {
                return ResourceManager.GetString("LRC_Error_Code_FailedToGetUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find this friend&apos;s info..
        /// </summary>
        internal static string LRC_Error_Code_FailedToLaunchGamercard {
            get {
                return ResourceManager.GetString("LRC_Error_Code_FailedToLaunchGamercard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem retrieving data from the service..
        /// </summary>
        internal static string LRC_Error_Code_FailedToRetrieveData {
            get {
                return ResourceManager.GetString("LRC_Error_Code_FailedToRetrieveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t send the command to the console. Please try again..
        /// </summary>
        internal static string LRC_Error_Code_FailedToSendCommand {
            get {
                return ResourceManager.GetString("LRC_Error_Code_FailedToSendCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, can&apos;t set your beacon right now. Try again later..
        /// </summary>
        internal static string LRC_Error_Code_FailedToSetBeacon {
            get {
                return ResourceManager.GetString("LRC_Error_Code_FailedToSetBeacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve set all 3 of your beacons. Remove one before setting another..
        /// </summary>
        internal static string LRC_Error_Code_FailedToSetBeacon_BeaconLimitReached {
            get {
                return ResourceManager.GetString("LRC_Error_Code_FailedToSetBeacon_BeaconLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment is too long..
        /// </summary>
        internal static string LRC_Error_Code_FailedToSetBeacon_BeaconTextTooLong {
            get {
                return ResourceManager.GetString("LRC_Error_Code_FailedToSetBeacon_BeaconTextTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t sign in to Xbox LIVE. Please try again..
        /// </summary>
        internal static string LRC_Error_Code_FailedToSignIn {
            get {
                return ResourceManager.GetString("LRC_Error_Code_FailedToSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was canceled. .
        /// </summary>
        internal static string LRC_Error_Code_RequestCancelled {
            get {
                return ResourceManager.GetString("LRC_Error_Code_RequestCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, couldn&apos;t start this on the console. Try again..
        /// </summary>
        internal static string MessageBody_LaunchOnConsoleFailed {
            get {
                return ResourceManager.GetString("MessageBody_LaunchOnConsoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast and crew not available..
        /// </summary>
        internal static string NoCastAndCrewFound {
            get {
                return ResourceManager.GetString("NoCastAndCrewFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found..
        /// </summary>
        internal static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out featured items or use Bing to search for content to play on your console..
        /// </summary>
        internal static string NowPlaying_Dashboard {
            get {
                return ResourceManager.GetString("NowPlaying_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discover more.
        /// </summary>
        internal static string NowPlaying_DiscoverMore {
            get {
                return ResourceManager.GetString("NowPlaying_DiscoverMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to featured.
        /// </summary>
        internal static string NowPlaying_FeatureHeader {
            get {
                return ResourceManager.GetString("NowPlaying_FeatureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less.
        /// </summary>
        internal static string NowPlaying_LessInfo {
            get {
                return ResourceManager.GetString("NowPlaying_LessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        internal static string NowPlaying_MoreInfo {
            get {
                return ResourceManager.GetString("NowPlaying_MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to achievements.
        /// </summary>
        internal static string NowPlaying_MoreInfo_Achievements {
            get {
                return ResourceManager.GetString("NowPlaying_MoreInfo_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.
        /// </summary>
        internal static string NowPlaying_MoreInfo_Artist {
            get {
                return ResourceManager.GetString("NowPlaying_MoreInfo_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cast &amp; crew.
        /// </summary>
        internal static string NowPlaying_MoreInfo_CastAndCrew {
            get {
                return ResourceManager.GetString("NowPlaying_MoreInfo_CastAndCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        internal static string NowPlaying_MoreInfo_Friends {
            get {
                return ResourceManager.GetString("NowPlaying_MoreInfo_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images.
        /// </summary>
        internal static string NowPlaying_MoreInfo_Images {
            get {
                return ResourceManager.GetString("NowPlaying_MoreInfo_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leaderboards.
        /// </summary>
        internal static string NowPlaying_MoreInfo_Leaderboards {
            get {
                return ResourceManager.GetString("NowPlaying_MoreInfo_Leaderboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overview.
        /// </summary>
        internal static string NowPlaying_MoreInfo_Overview {
            get {
                return ResourceManager.GetString("NowPlaying_MoreInfo_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to related.
        /// </summary>
        internal static string NowPlaying_MoreInfo_Related {
            get {
                return ResourceManager.GetString("NowPlaying_MoreInfo_Related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review.
        /// </summary>
        internal static string NowPlaying_MoreInfo_Review {
            get {
                return ResourceManager.GetString("NowPlaying_MoreInfo_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on your console.
        /// </summary>
        internal static string NowPlaying_OnYourXbox {
            get {
                return ResourceManager.GetString("NowPlaying_OnYourXbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overview.
        /// </summary>
        internal static string NowPlaying_Overview_Header {
            get {
                return ResourceManager.GetString("NowPlaying_Overview_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quickplay.
        /// </summary>
        internal static string NowPlaying_RecentlyPlayedHeader {
            get {
                return ResourceManager.GetString("NowPlaying_RecentlyPlayedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing.
        /// </summary>
        internal static string NowPlaying_SearchHeader {
            get {
                return ResourceManager.GetString("NowPlaying_SearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:00}:{1:00}:{2:00}.
        /// </summary>
        internal static string NowPlaying_TimeSpan_Format {
            get {
                return ResourceManager.GetString("NowPlaying_TimeSpan_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zune Video Marketplace.
        /// </summary>
        internal static string NowPlaying_ZuneMarketplaceTitle {
            get {
                return ResourceManager.GetString("NowPlaying_ZuneMarketplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show less.
        /// </summary>
        internal static string NowPlayingAlbums_ShowLess {
            get {
                return ResourceManager.GetString("NowPlayingAlbums_ShowLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show more.
        /// </summary>
        internal static string NowPlayingAlbums_ShowMore {
            get {
                return ResourceManager.GetString("NowPlayingAlbums_ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        internal static string NowPlayingHeader {
            get {
                return ResourceManager.GetString("NowPlayingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        internal static string NowPlayingMediaProgress {
            get {
                return ResourceManager.GetString("NowPlayingMediaProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide.
        /// </summary>
        internal static string NowPlayingSongs_Hide {
            get {
                return ResourceManager.GetString("NowPlayingSongs_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        internal static string NowPlayingSongs_Show {
            get {
                return ResourceManager.GetString("NowPlayingSongs_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        internal static string OK_Text {
            get {
                return ResourceManager.GetString("OK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overview.
        /// </summary>
        internal static string Overview_Header {
            get {
                return ResourceManager.GetString("Overview_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string ProviderOffer_Free {
            get {
                return ResourceManager.GetString("ProviderOffer_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free with Ads.
        /// </summary>
        internal static string ProviderOffer_FreeWithAds {
            get {
                return ResourceManager.GetString("ProviderOffer_FreeWithAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string ProviderOffer_FreeWithSubscription {
            get {
                return ResourceManager.GetString("ProviderOffer_FreeWithSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Per View.
        /// </summary>
        internal static string ProviderOffer_PayPerView {
            get {
                return ResourceManager.GetString("ProviderOffer_PayPerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string ProviderOffer_Purchase {
            get {
                return ResourceManager.GetString("ProviderOffer_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        internal static string ProviderOffer_Rent {
            get {
                return ResourceManager.GetString("ProviderOffer_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent items..
        /// </summary>
        internal static string QuickLaunch_NoRecentItems {
            get {
                return ResourceManager.GetString("QuickLaunch_NoRecentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        internal static string Refresh_SetRefreshButtonText {
            get {
                return ResourceManager.GetString("Refresh_SetRefreshButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to related.
        /// </summary>
        internal static string Related_Header {
            get {
                return ResourceManager.GetString("Related_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No related items are currently available..
        /// </summary>
        internal static string RelatedItems_NoResultsFound {
            get {
                return ResourceManager.GetString("RelatedItems_NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | .
        /// </summary>
        internal static string Search_DetailsSeparator {
            get {
                return ResourceManager.GetString("Search_DetailsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, search isn&apos;t available. Try again in a while..
        /// </summary>
        internal static string Search_ErrorText {
            get {
                return ResourceManager.GetString("Search_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found for {0}..
        /// </summary>
        internal static string Search_NoResultsText {
            get {
                return ResourceManager.GetString("Search_NoResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play on your console:.
        /// </summary>
        internal static string Search_PlayOnXbox {
            get {
                return ResourceManager.GetString("Search_PlayOnXbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        internal static string Search_UserVoterCount {
            get {
                return ResourceManager.GetString("Search_UserVoterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images found..
        /// </summary>
        internal static string SearchGameDetail_NoImages {
            get {
                return ResourceManager.GetString("SearchGameDetail_NoImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search Xbox for.
        /// </summary>
        internal static string SearchHelpText_BasicPrompt {
            get {
                return ResourceManager.GetString("SearchHelpText_BasicPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search Xbox for movies,.
        /// </summary>
        internal static string SearchHelpText_Prompt1_Category1 {
            get {
                return ResourceManager.GetString("SearchHelpText_Prompt1_Category1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search Xbox for albums,.
        /// </summary>
        internal static string SearchHelpText_Prompt1_Category2 {
            get {
                return ResourceManager.GetString("SearchHelpText_Prompt1_Category2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search Xbox for games,.
        /// </summary>
        internal static string SearchHelpText_Prompt1_Category3 {
            get {
                return ResourceManager.GetString("SearchHelpText_Prompt1_Category3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search Xbox for movies, TV....
        /// </summary>
        internal static string SearchHelpText_Prompt2_Category1 {
            get {
                return ResourceManager.GetString("SearchHelpText_Prompt2_Category1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search Xbox for albums, artists....
        /// </summary>
        internal static string SearchHelpText_Prompt2_Category2 {
            get {
                return ResourceManager.GetString("SearchHelpText_Prompt2_Category2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search Xbox for games, apps....
        /// </summary>
        internal static string SearchHelpText_Prompt2_Category3 {
            get {
                return ResourceManager.GetString("SearchHelpText_Prompt2_Category3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching . . ..
        /// </summary>
        internal static string SearchResult_BusyIndicatorText {
            get {
                return ResourceManager.GetString("SearchResult_BusyIndicatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string SearchResultFilterItem_All {
            get {
                return ResourceManager.GetString("SearchResultFilterItem_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps.
        /// </summary>
        internal static string SearchResultFilterItem_Apps {
            get {
                return ResourceManager.GetString("SearchResultFilterItem_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to games.
        /// </summary>
        internal static string SearchResultFilterItem_Games {
            get {
                return ResourceManager.GetString("SearchResultFilterItem_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movies.
        /// </summary>
        internal static string SearchResultFilterItem_Movies {
            get {
                return ResourceManager.GetString("SearchResultFilterItem_Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to music.
        /// </summary>
        internal static string SearchResultFilterItem_Music {
            get {
                return ResourceManager.GetString("SearchResultFilterItem_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tv shows.
        /// </summary>
        internal static string SearchResultFilterItem_TV {
            get {
                return ResourceManager.GetString("SearchResultFilterItem_TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string SearchResultFilterSummary {
            get {
                return ResourceManager.GetString("SearchResultFilterSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        internal static string SearchResults_FilterHeader {
            get {
                return ResourceManager.GetString("SearchResults_FilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        internal static string SearchResults_PageTitle {
            get {
                return ResourceManager.GetString("SearchResults_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string SearchResults_StartSearch {
            get {
                return ResourceManager.GetString("SearchResults_StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popular now.
        /// </summary>
        internal static string SearchTerms_Title {
            get {
                return ResourceManager.GetString("SearchTerms_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        internal static string SigningInMessage {
            get {
                return ResourceManager.GetString("SigningInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the best experience, the console and your Windows Phone should be on the same network..
        /// </summary>
        internal static string SlowConnectionDescription1 {
            get {
                return ResourceManager.GetString("SlowConnectionDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To connect, go to Settings, Wi-Fi, then choose the same network your console is on. Xbox Companion will work on a separate network, but it may affect performance..
        /// </summary>
        internal static string SlowConnectionDescription2 {
            get {
                return ResourceManager.GetString("SlowConnectionDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow connection detected.
        /// </summary>
        internal static string SlowConnectionDetected_Header {
            get {
                return ResourceManager.GetString("SlowConnectionDetected_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string SuccessfulConnectionPage_ContinueButtonText {
            get {
                return ResourceManager.GetString("SuccessfulConnectionPage_ContinueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string SuccessfulConnectionPage_Header {
            get {
                return ResourceManager.GetString("SuccessfulConnectionPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re now connected to your Xbox 360 console..
        /// </summary>
        internal static string SuccessfulConnectionPage_InformationalText_Section1 {
            get {
                return ResourceManager.GetString("SuccessfulConnectionPage_InformationalText_Section1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your Windows Phone to find videos, music, games, and more, and play them directly on your console..
        /// </summary>
        internal static string SuccessfulConnectionPage_InformationalText_Section2 {
            get {
                return ResourceManager.GetString("SuccessfulConnectionPage_InformationalText_Section2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to synopsis.
        /// </summary>
        internal static string Synopsis_Header {
            get {
                return ResourceManager.GetString("Synopsis_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available for this app. This update is required to continue using Xbox Companion..
        /// </summary>
        internal static string TitleUpdate_Text {
            get {
                return ResourceManager.GetString("TitleUpdate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update required.
        /// </summary>
        internal static string TitleUpdate_Title {
            get {
                return ResourceManager.GetString("TitleUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string TVDetails_DescriptionHeader {
            get {
                return ResourceManager.GetString("TVDetails_DescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seasons.
        /// </summary>
        internal static string TVDetails_SeasonsHeader {
            get {
                return ResourceManager.GetString("TVDetails_SeasonsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: season {1}.
        /// </summary>
        internal static string TVDetailsTitle {
            get {
                return ResourceManager.GetString("TVDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode {0}.
        /// </summary>
        internal static string TVEpisodeTitle {
            get {
                return ResourceManager.GetString("TVEpisodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season {0}.
        /// </summary>
        internal static string TVSeasonTitle {
            get {
                return ResourceManager.GetString("TVSeasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        internal static string Warning_Title {
            get {
                return ResourceManager.GetString("Warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writer.
        /// </summary>
        internal static string Writer_Header {
            get {
                return ResourceManager.GetString("Writer_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writers.
        /// </summary>
        internal static string Writers_Header {
            get {
                return ResourceManager.GetString("Writers_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spotlight.
        /// </summary>
        internal static string ZuneMarketplace_FeaturedHeader {
            get {
                return ResourceManager.GetString("ZuneMarketplace_FeaturedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movies.
        /// </summary>
        internal static string ZuneMarketplace_MoviesHeader {
            get {
                return ResourceManager.GetString("ZuneMarketplace_MoviesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picks for me.
        /// </summary>
        internal static string ZuneMarketplace_PicksForYouHeader {
            get {
                return ResourceManager.GetString("ZuneMarketplace_PicksForYouHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tv.
        /// </summary>
        internal static string ZuneMarketplace_TVHeader {
            get {
                return ResourceManager.GetString("ZuneMarketplace_TVHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zune Music.
        /// </summary>
        internal static string ZuneMusic_ProviderName {
            get {
                return ResourceManager.GetString("ZuneMusic_ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zune Video.
        /// </summary>
        internal static string ZuneVideo_ProviderName {
            get {
                return ResourceManager.GetString("ZuneVideo_ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genres.
        /// </summary>
        internal static string ZuneVideoMarketPlace_Genres {
            get {
                return ResourceManager.GetString("ZuneVideoMarketPlace_Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to videos.
        /// </summary>
        internal static string ZuneVideoMarketPlace_HubTitle {
            get {
                return ResourceManager.GetString("ZuneVideoMarketPlace_HubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zune video marketplace.
        /// </summary>
        internal static string ZuneVideoMarketPlace_MaketplaceTitle {
            get {
                return ResourceManager.GetString("ZuneVideoMarketPlace_MaketplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to network.
        /// </summary>
        internal static string ZuneVideoMarketPlace_Network {
            get {
                return ResourceManager.GetString("ZuneVideoMarketPlace_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new releases.
        /// </summary>
        internal static string ZuneVideoMarketPlace_NewReleases {
            get {
                return ResourceManager.GetString("ZuneVideoMarketPlace_NewReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to release date.
        /// </summary>
        internal static string ZuneVideoMarketPlace_ReleaseDateFilter {
            get {
                return ResourceManager.GetString("ZuneVideoMarketPlace_ReleaseDateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to studios.
        /// </summary>
        internal static string ZuneVideoMarketPlace_Studios {
            get {
                return ResourceManager.GetString("ZuneVideoMarketPlace_Studios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string ZuneVideoMarketPlace_TitleFilter {
            get {
                return ResourceManager.GetString("ZuneVideoMarketPlace_TitleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top purchased.
        /// </summary>
        internal static string ZuneVideoMarketPlace_TopPurchases {
            get {
                return ResourceManager.GetString("ZuneVideoMarketPlace_TopPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top rented.
        /// </summary>
        internal static string ZuneVideoMarketPlace_TopRentalFilter {
            get {
                return ResourceManager.GetString("ZuneVideoMarketPlace_TopRentalFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top rented.
        /// </summary>
        internal static string ZuneVideoMarketPlace_TopRentals {
            get {
                return ResourceManager.GetString("ZuneVideoMarketPlace_TopRentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top selling.
        /// </summary>
        internal static string ZuneVideoMarketPlace_TopSellingFilter {
            get {
                return ResourceManager.GetString("ZuneVideoMarketPlace_TopSellingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to episode {0}.
        /// </summary>
        internal static string ZuneVideoMarketPlace_TV_EpisodeNumber {
            get {
                return ResourceManager.GetString("ZuneVideoMarketPlace_TV_EpisodeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to season {0}.
        /// </summary>
        internal static string ZuneVideoMarketPlace_TV_EpisodeTitle {
            get {
                return ResourceManager.GetString("ZuneVideoMarketPlace_TV_EpisodeTitle", resourceCulture);
            }
        }
    }
}
