//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xbox.Live.Phone.Utils.Xbox.Live.Phone.Utils.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xbox.Live.Phone.Utils.Xbox.Live.Phone.Utils.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find your avatar, please try again later..
        /// </summary>
        internal static string AvatarFailedToDownloadAssets {
            get {
                return ResourceManager.GetString("AvatarFailedToDownloadAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find your prop, please try again later..
        /// </summary>
        internal static string AvatarFailedToDownloadPropAnimation {
            get {
                return ResourceManager.GetString("AvatarFailedToDownloadPropAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The avatar information is not valid, please create a new avatar..
        /// </summary>
        internal static string AvatarInvalidManifest {
            get {
                return ResourceManager.GetString("AvatarInvalidManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string CancelButton_Text {
            get {
                return ResourceManager.GetString("CancelButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error_ErrorMessage_Title {
            get {
                return ResourceManager.GetString("Error_ErrorMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string Error_StandardException_Title {
            get {
                return ResourceManager.GetString("Error_StandardException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        internal static string ErrorNonfatalError {
            get {
                return ResourceManager.GetString("ErrorNonfatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        internal static string OkButton_Text {
            get {
                return ResourceManager.GetString("OkButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The type or action for error code {0} is invalid..
        /// </summary>
        internal static string ProgrammingError_InvalidTypeOrAction {
            get {
                return ResourceManager.GetString("ProgrammingError_InvalidTypeOrAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot find error code {0}..
        /// </summary>
        internal static string ProgrammingError_NoErrorStringInResource {
            get {
                return ResourceManager.GetString("ProgrammingError_NoErrorStringInResource", resourceCulture);
            }
        }
    }
}
