//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.XboxLive.Avatars.Internal.Software {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.XboxLive.Avatars.Internal.Software.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 584D07D1.
        /// </summary>
        internal static string AvatarEditorTitleId {
            get {
                return ResourceManager.GetString("AvatarEditorTitleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted data stream.
        /// </summary>
        internal static string CorruptedStreamText {
            get {
                return ResourceManager.GetString("CorruptedStreamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset decompression failed..
        /// </summary>
        internal static string DecompressionFailedText {
            get {
                return ResourceManager.GetString("DecompressionFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download animation asset.
        /// </summary>
        internal static string FailedToDownloadAnimationAssetText {
            get {
                return ResourceManager.GetString("FailedToDownloadAnimationAssetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download asset.
        /// </summary>
        internal static string FailedToDownloadAssetText {
            get {
                return ResourceManager.GetString("FailedToDownloadAssetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load required avatar asset(s). Asset service may be down, is unreachable or asset is not available..
        /// </summary>
        internal static string FailedToLoadAssetText {
            get {
                return ResourceManager.GetString("FailedToLoadAssetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load core asset. Asset service may be down or is unreachable..
        /// </summary>
        internal static string FailedToLoadCoreAssetText {
            get {
                return ResourceManager.GetString("FailedToLoadCoreAssetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse animation asset file.
        /// </summary>
        internal static string FailedToParseAnimationAssetFileText {
            get {
                return ResourceManager.GetString("FailedToParseAnimationAssetFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve eyeshadow texture for given eye.
        /// </summary>
        internal static string FailedToResolveEyeShadowTexture {
            get {
                return ResourceManager.GetString("FailedToResolveEyeShadowTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset gender does not match avatar body gender..
        /// </summary>
        internal static string IncompatibleAssetGenderText {
            get {
                return ResourceManager.GetString("IncompatibleAssetGenderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid avatar manifest. Cannot combine incompatible assets..
        /// </summary>
        internal static string IncompatibleAssetsText {
            get {
                return ResourceManager.GetString("IncompatibleAssetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid animation asset file.
        /// </summary>
        internal static string InvalidAnimationAssetFileText {
            get {
                return ResourceManager.GetString("InvalidAnimationAssetFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid asset type..
        /// </summary>
        internal static string InvalidAssetTypeText {
            get {
                return ResourceManager.GetString("InvalidAssetTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid avatar expression format.
        /// </summary>
        internal static string InvalidAvatarExpressionFormatText {
            get {
                return ResourceManager.GetString("InvalidAvatarExpressionFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid eyebrow texture index.
        /// </summary>
        internal static string InvalidAvatarEyebrowTextureIndex {
            get {
                return ResourceManager.GetString("InvalidAvatarEyebrowTextureIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid eye texture index.
        /// </summary>
        internal static string InvalidAvatarEyeTextureIndex {
            get {
                return ResourceManager.GetString("InvalidAvatarEyeTextureIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mouth texture index.
        /// </summary>
        internal static string InvalidAvatarMouthTextureIndex {
            get {
                return ResourceManager.GetString("InvalidAvatarMouthTextureIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid avatar component ID.
        /// </summary>
        internal static string InvalidComponentIdText {
            get {
                return ResourceManager.GetString("InvalidComponentIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of custom colors. 3 are required..
        /// </summary>
        internal static string InvalidCustomColorsText {
            get {
                return ResourceManager.GetString("InvalidCustomColorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid manifest, failed to equip required components.
        /// </summary>
        internal static string InvalidManifest1 {
            get {
                return ResourceManager.GetString("InvalidManifest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid manifest, required components not present.
        /// </summary>
        internal static string InvalidManifest2 {
            get {
                return ResourceManager.GetString("InvalidManifest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid manifest, body is required but not present.
        /// </summary>
        internal static string InvalidManifest3 {
            get {
                return ResourceManager.GetString("InvalidManifest3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid manifest, head is required but not present.
        /// </summary>
        internal static string InvalidManifest4 {
            get {
                return ResourceManager.GetString("InvalidManifest4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid manifest, head is required but required blend shapes are not present.
        /// </summary>
        internal static string InvalidManifest5 {
            get {
                return ResourceManager.GetString("InvalidManifest5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid manifest, head is required but required textures are not present.
        /// </summary>
        internal static string InvalidManifest6 {
            get {
                return ResourceManager.GetString("InvalidManifest6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid skeleton version..
        /// </summary>
        internal static string InvalidSkeletonVersion {
            get {
                return ResourceManager.GetString("InvalidSkeletonVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid structured binary file.
        /// </summary>
        internal static string InvalidStrbFileText {
            get {
                return ResourceManager.GetString("InvalidStrbFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid word size.
        /// </summary>
        internal static string InvalidWordSizeText {
            get {
                return ResourceManager.GetString("InvalidWordSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid calling thread.
        /// </summary>
        internal static string IvalidCallingThread {
            get {
                return ResourceManager.GetString("IvalidCallingThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronous download can&apos;t be called from Main Thread.
        /// </summary>
        internal static string MainThreadExceptionText {
            get {
                return ResourceManager.GetString("MainThreadExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest cannot be null.
        /// </summary>
        internal static string ManifestCannotBeNullText {
            get {
                return ResourceManager.GetString("ManifestCannotBeNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest components validation failed..
        /// </summary>
        internal static string ManifestValidationFailed {
            get {
                return ResourceManager.GetString("ManifestValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many batches per avatar component.
        /// </summary>
        internal static string ModelParserError1 {
            get {
                return ResourceManager.GetString("ModelParserError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many textures per avatar component.
        /// </summary>
        internal static string ModelParserError2 {
            get {
                return ResourceManager.GetString("ModelParserError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex pairs count out of range.
        /// </summary>
        internal static string ModelParserError3 {
            get {
                return ResourceManager.GetString("ModelParserError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex pairing index out of range.
        /// </summary>
        internal static string ModelParserError4 {
            get {
                return ResourceManager.GetString("ModelParserError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost/AvatarResources/Assets/{0}.bin.
        /// </summary>
        internal static string NonStockAssetAddressFormat {
            get {
                return ResourceManager.GetString("NonStockAssetAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape overrides dictionary failed to load.
        /// </summary>
        internal static string ShapeOverridesFaiedToLoad {
            get {
                return ResourceManager.GetString("ShapeOverridesFaiedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape overrides dictionary failed to load.
        /// </summary>
        internal static string ShapeOverridesFailedToLoad {
            get {
                return ResourceManager.GetString("ShapeOverridesFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many joints in skeleton.
        /// </summary>
        internal static string SkeletonParserError1 {
            get {
                return ResourceManager.GetString("SkeletonParserError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost/AvatarResources/Assets/{0}.bin.
        /// </summary>
        internal static string StockAssetAddressFormat {
            get {
                return ResourceManager.GetString("StockAssetAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid texture width.
        /// </summary>
        internal static string TextureParserError1 {
            get {
                return ResourceManager.GetString("TextureParserError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid texture height.
        /// </summary>
        internal static string TextureParserError2 {
            get {
                return ResourceManager.GetString("TextureParserError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture layer count out of range.
        /// </summary>
        internal static string TextureParserError3 {
            get {
                return ResourceManager.GetString("TextureParserError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid texture format descriptor.
        /// </summary>
        internal static string TextureParserError4 {
            get {
                return ResourceManager.GetString("TextureParserError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle count out of range.
        /// </summary>
        internal static string TriangleOverrideError1 {
            get {
                return ResourceManager.GetString("TriangleOverrideError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture coordinates count out of range.
        /// </summary>
        internal static string TriangleParserError1 {
            get {
                return ResourceManager.GetString("TriangleParserError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle count out of range.
        /// </summary>
        internal static string TriangleParserError2 {
            get {
                return ResourceManager.GetString("TriangleParserError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex count out of range.
        /// </summary>
        internal static string TriangleParserError3 {
            get {
                return ResourceManager.GetString("TriangleParserError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid vertex stride.
        /// </summary>
        internal static string TriangleParserError4 {
            get {
                return ResourceManager.GetString("TriangleParserError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of triangles in asset stream.
        /// </summary>
        internal static string TriangleParserError5 {
            get {
                return ResourceManager.GetString("TriangleParserError5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of vertices in asset stream.
        /// </summary>
        internal static string TriangleParserError6 {
            get {
                return ResourceManager.GetString("TriangleParserError6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid shader type.
        /// </summary>
        internal static string TriangleParserError7 {
            get {
                return ResourceManager.GetString("TriangleParserError7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file while parsing assets.
        /// </summary>
        internal static string UnexpectedEofText {
            get {
                return ResourceManager.GetString("UnexpectedEofText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized asset version specified as an input parameter..
        /// </summary>
        internal static string UnknownAssetVersionText {
            get {
                return ResourceManager.GetString("UnknownAssetVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex count out of range.
        /// </summary>
        internal static string VertexOverrideError1 {
            get {
                return ResourceManager.GetString("VertexOverrideError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex override index out of range.
        /// </summary>
        internal static string VertexOverrideError2 {
            get {
                return ResourceManager.GetString("VertexOverrideError2", resourceCulture);
            }
        }
    }
}
