// *********************************************************
// Type: LRC.Resources.RatingStringsHelper
// Assembly: LRC.Resource, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 9093DA41-95AA-481C-B970-06E86E67D53B
// *********************************************************LRC.Resource.dll

using System;
using System.Collections.Generic;
using System.Globalization;


namespace LRC.Resources
{
  public static class RatingStringsHelper
  {
    private const string UnratedRating = "Unrated";
    private const string UnratedRatingKey = "PARENTAL_UNRATED";
    private const string RatingMovieKeyFormat = "PARENTAL_RATING_{0}_{1}";
    private const string RatingTVKeyFormat = "PARENTAL_RATING_{0}{1}_{2}";
    private static Dictionary<string, string> liveRatingLevel = new Dictionary<string, string>()
    {
      {
        "0",
        "PARENTAL_RATING_ESRB_EC"
      },
      {
        "10",
        "PARENTAL_RATING_ESRB_E"
      },
      {
        "20",
        "PARENTAL_RATING_ESRB_E10"
      },
      {
        "25",
        "PARENTAL_RATING_ESRB_E10_RP"
      },
      {
        "30",
        "PARENTAL_RATING_ESRB_T"
      },
      {
        "40",
        "PARENTAL_RATING_ESRB_M"
      },
      {
        "50",
        "PARENTAL_RATING_ESRB_AO"
      },
      {
        "60",
        "PARENTAL_UNRATED_OR_PENDING"
      },
      {
        "100",
        "PARENTAL_RATING_CERO_A"
      },
      {
        "110",
        "PARENTAL_RATING_CERO_B"
      },
      {
        "120",
        "PARENTAL_RATING_CERO_C"
      },
      {
        "130",
        "PARENTAL_RATING_CERO_D"
      },
      {
        "140",
        "PARENTAL_RATING_CERO_Z"
      },
      {
        "150",
        "PARENTAL_UNRATED_OR_PENDING"
      },
      {
        "4001",
        "PARENTAL_RATING_PEGI_3"
      },
      {
        "4002",
        "PARENTAL_RATING_PEGI_7"
      },
      {
        "4003",
        "PARENTAL_RATING_PEGI_12"
      },
      {
        "4004",
        "PARENTAL_RATING_PEGI_16"
      },
      {
        "4005",
        "PARENTAL_RATING_PEGI_18"
      },
      {
        "5001",
        "PARENTAL_RATING_PEGI_4"
      },
      {
        "5002",
        "PARENTAL_RATING_PEGI_6"
      },
      {
        "5003",
        "PARENTAL_RATING_PEGI_12"
      },
      {
        "5004",
        "PARENTAL_RATING_PEGI_16"
      },
      {
        "5005",
        "PARENTAL_RATING_PEGI_18"
      },
      {
        "7001",
        "PARENTAL_RATING_USK_ALL_AGES"
      },
      {
        "7002",
        "PARENTAL_RATING_USK_6"
      },
      {
        "7003",
        "PARENTAL_RATING_USK_12"
      },
      {
        "7004",
        "PARENTAL_RATING_USK_16"
      },
      {
        "7005",
        "PARENTAL_RATING_USK_NO_YOUTH"
      },
      {
        "7006",
        "PARENTAL_UNRATED_OR_PENDING"
      },
      {
        "8001",
        "PARENTAL_RATING_OFLC_AU_G"
      },
      {
        "8002",
        "PARENTAL_RATING_OFLC_AU_G8"
      },
      {
        "8003",
        "PARENTAL_RATING_OFLC_AU_M15"
      },
      {
        "8004",
        "PARENTAL_RATING_OFLC_AU_MA15"
      },
      {
        "8005",
        "PARENTAL_RATING_OFLC_AU_REFUSED"
      },
      {
        "8006",
        "PARENTAL_RATING_OFLC_AU_E"
      },
      {
        "8007",
        "PARENTAL_RATING_OFLC_AU_G"
      },
      {
        "8008",
        "PARENTAL_RATING_OFLC_AU_PG"
      },
      {
        "8009",
        "PARENTAL_RATING_OFLC_AU_M"
      },
      {
        "8010",
        "PARENTAL_RATING_OFLC_AU_MA15"
      },
      {
        "8011",
        "PARENTAL_RATING_OFLC_AU_R18"
      },
      {
        "8012",
        "PARENTAL_RATING_OFLC_AU_X18"
      },
      {
        "9001",
        "PARENTAL_RATING_OFLC_NZ_G"
      },
      {
        "9002",
        "PARENTAL_RATING_OFLC_NZ_PG"
      },
      {
        "9003",
        "PARENTAL_RATING_OFLC_NZ_M"
      },
      {
        "9004",
        "PARENTAL_RATING_OFLC_NZ_R15"
      },
      {
        "9005",
        "PARENTAL_RATING_OFLC_NZ_R"
      },
      {
        "9006",
        "PARENTAL_RATING_OFLC_NZ_R13"
      },
      {
        "9007",
        "PARENTAL_RATING_OFLC_NZ_R16"
      },
      {
        "9008",
        "PARENTAL_RATING_OFLC_NZ_R18"
      },
      {
        "11001",
        "PARENTAL_RATING_KMRB_ALL"
      },
      {
        "11002",
        "PARENTAL_RATING_KMRB_12"
      },
      {
        "11003",
        "PARENTAL_RATING_KMRB_15"
      },
      {
        "11004",
        "PARENTAL_RATING_KMRB_18"
      },
      {
        "13001",
        "PARENTAL_RATING_FPB_A"
      },
      {
        "13002",
        "PARENTAL_RATING_FPB_PG"
      },
      {
        "13003",
        "PARENTAL_RATING_FPB_10"
      },
      {
        "13004",
        "PARENTAL_RATING_FPB_13"
      },
      {
        "13005",
        "PARENTAL_RATING_FPB_16"
      },
      {
        "13006",
        "PARENTAL_RATING_FPB_18"
      },
      {
        "13007",
        "PARENTAL_RATING_FPB_PG"
      },
      {
        "12006",
        "PARENTAL_RATING_BRAZIL_ER"
      },
      {
        "12001",
        "PARENTAL_RATING_BRAZIL_L"
      },
      {
        "12007",
        "PARENTAL_RATING_BRAZIL_10"
      },
      {
        "12002",
        "PARENTAL_RATING_BRAZIL_12"
      },
      {
        "12003",
        "PARENTAL_RATING_BRAZIL_14"
      },
      {
        "12004",
        "PARENTAL_RATING_BRAZIL_16"
      },
      {
        "12005",
        "PARENTAL_RATING_BRAZIL_18"
      },
      {
        "14001",
        "PARENTAL_RATING_PEGI_3"
      },
      {
        "14002",
        "PARENTAL_RATING_PEGI_7"
      },
      {
        "14003",
        "PARENTAL_RATING_PEGI_12"
      },
      {
        "14004",
        "PARENTAL_RATING_PEGI_16"
      },
      {
        "14005",
        "PARENTAL_RATING_PEGI_18"
      },
      {
        "17001",
        "PARENTAL_RATING_TAIWAN_GENERAL"
      },
      {
        "17002",
        "PARENTAL_RATING_TAIWAN_PROTECTED"
      },
      {
        "17003",
        "PARENTAL_RATING_TAIWAN_PG"
      },
      {
        "17004",
        "PARENTAL_RATING_TAIWAN_RESTRICTED"
      },
      {
        "18001",
        "PARENTAL_RATING_SINGAPORE_GENERAL"
      },
      {
        "18002",
        "PARENTAL_RATING_SINGAPORE_AGE_ADVISORY"
      },
      {
        "18003",
        "PARENTAL_RATING_SINGAPORE_MATURE_18"
      }
    };
    private static Dictionary<string, string> liveRatingDescriptor = new Dictionary<string, string>()
    {
      {
        "0",
        "PARENTAL_RATING_DESCRIPTOR_0"
      },
      {
        "1",
        "PARENTAL_RATING_DESCRIPTOR_1"
      },
      {
        "2",
        "PARENTAL_RATING_DESCRIPTOR_2"
      },
      {
        "3",
        "PARENTAL_RATING_DESCRIPTOR_3"
      },
      {
        "4",
        "PARENTAL_RATING_DESCRIPTOR_4"
      },
      {
        "5",
        "PARENTAL_RATING_DESCRIPTOR_5"
      },
      {
        "6",
        "PARENTAL_RATING_DESCRIPTOR_6"
      },
      {
        "7",
        "PARENTAL_RATING_DESCRIPTOR_7"
      },
      {
        "8",
        "PARENTAL_RATING_DESCRIPTOR_8"
      },
      {
        "9",
        "PARENTAL_RATING_DESCRIPTOR_9"
      },
      {
        "10",
        "PARENTAL_RATING_DESCRIPTOR_10"
      },
      {
        "11",
        "PARENTAL_RATING_DESCRIPTOR_11"
      },
      {
        "12",
        "PARENTAL_RATING_DESCRIPTOR_12"
      },
      {
        "13",
        "PARENTAL_RATING_DESCRIPTOR_13"
      },
      {
        "14",
        "PARENTAL_RATING_DESCRIPTOR_14"
      },
      {
        "15",
        "PARENTAL_RATING_DESCRIPTOR_15"
      },
      {
        "16",
        "PARENTAL_RATING_DESCRIPTOR_16"
      },
      {
        "17",
        "PARENTAL_RATING_DESCRIPTOR_17"
      },
      {
        "18",
        "PARENTAL_RATING_DESCRIPTOR_18"
      },
      {
        "19",
        "PARENTAL_RATING_DESCRIPTOR_19"
      },
      {
        "20",
        "PARENTAL_RATING_DESCRIPTOR_20"
      },
      {
        "21",
        "PARENTAL_RATING_DESCRIPTOR_21"
      },
      {
        "22",
        "PARENTAL_RATING_DESCRIPTOR_22"
      },
      {
        "23",
        "PARENTAL_RATING_DESCRIPTOR_23"
      },
      {
        "24",
        "PARENTAL_RATING_DESCRIPTOR_24"
      },
      {
        "25",
        "PARENTAL_RATING_DESCRIPTOR_25"
      },
      {
        "26",
        "PARENTAL_RATING_DESCRIPTOR_26"
      },
      {
        "27",
        "PARENTAL_RATING_DESCRIPTOR_27"
      },
      {
        "28",
        "PARENTAL_RATING_DESCRIPTOR_28"
      },
      {
        "29",
        "PARENTAL_RATING_DESCRIPTOR_29"
      },
      {
        "30",
        "PARENTAL_RATING_DESCRIPTOR_30"
      },
      {
        "31",
        "PARENTAL_RATING_DESCRIPTOR_31"
      },
      {
        "32",
        "PARENTAL_RATING_DESCRIPTOR_32"
      },
      {
        "33",
        "PARENTAL_RATING_DESCRIPTOR_33"
      },
      {
        "34",
        "PARENTAL_RATING_DESCRIPTOR_34"
      },
      {
        "35",
        "PARENTAL_RATING_DESCRIPTOR_35"
      },
      {
        "36",
        "PARENTAL_RATING_DESCRIPTOR_36"
      },
      {
        "37",
        "PARENTAL_RATING_DESCRIPTOR_37"
      },
      {
        "38",
        "PARENTAL_RATING_DESCRIPTOR_38"
      },
      {
        "39",
        "PARENTAL_RATING_DESCRIPTOR_39"
      },
      {
        "40",
        "PARENTAL_RATING_DESCRIPTOR_40"
      },
      {
        "41",
        "PARENTAL_RATING_DESCRIPTOR_41"
      },
      {
        "42",
        "PARENTAL_RATING_DESCRIPTOR_42"
      },
      {
        "43",
        "PARENTAL_RATING_DESCRIPTOR_43"
      },
      {
        "44",
        "PARENTAL_RATING_DESCRIPTOR_44"
      },
      {
        "45",
        "PARENTAL_RATING_DESCRIPTOR_45"
      },
      {
        "46",
        "PARENTAL_RATING_DESCRIPTOR_46"
      },
      {
        "47",
        "PARENTAL_RATING_DESCRIPTOR_47"
      },
      {
        "48",
        "PARENTAL_RATING_DESCRIPTOR_48"
      },
      {
        "49",
        "PARENTAL_RATING_DESCRIPTOR_49"
      },
      {
        "50",
        "PARENTAL_RATING_DESCRIPTOR_50"
      },
      {
        "51",
        "PARENTAL_RATING_DESCRIPTOR_51"
      },
      {
        "52",
        "PARENTAL_RATING_DESCRIPTOR_52"
      },
      {
        "53",
        "PARENTAL_RATING_DESCRIPTOR_53"
      },
      {
        "54",
        "PARENTAL_RATING_DESCRIPTOR_54"
      },
      {
        "55",
        "PARENTAL_RATING_DESCRIPTOR_55"
      },
      {
        "56",
        "PARENTAL_RATING_DESCRIPTOR_56"
      },
      {
        "57",
        "PARENTAL_RATING_DESCRIPTOR_57"
      },
      {
        "58",
        "PARENTAL_RATING_DESCRIPTOR_58"
      },
      {
        "59",
        "PARENTAL_RATING_DESCRIPTOR_59"
      },
      {
        "60",
        "PARENTAL_RATING_DESCRIPTOR_60"
      },
      {
        "61",
        "PARENTAL_RATING_DESCRIPTOR_61"
      },
      {
        "62",
        "PARENTAL_RATING_DESCRIPTOR_62"
      },
      {
        "63",
        "PARENTAL_RATING_DESCRIPTOR_63"
      },
      {
        "64",
        "PARENTAL_RATING_DESCRIPTOR_64"
      },
      {
        "65",
        "PARENTAL_RATING_DESCRIPTOR_65"
      },
      {
        "66",
        "PARENTAL_RATING_DESCRIPTOR_66"
      },
      {
        "67",
        "PARENTAL_RATING_DESCRIPTOR_67"
      },
      {
        "68",
        "PARENTAL_RATING_DESCRIPTOR_68"
      },
      {
        "69",
        "PARENTAL_RATING_DESCRIPTOR_69"
      },
      {
        "70",
        "PARENTAL_RATING_DESCRIPTOR_70"
      },
      {
        "71",
        "PARENTAL_RATING_DESCRIPTOR_71"
      },
      {
        "72",
        "PARENTAL_RATING_DESCRIPTOR_72"
      },
      {
        "73",
        "PARENTAL_RATING_DESCRIPTOR_73"
      },
      {
        "74",
        "PARENTAL_RATING_DESCRIPTOR_74"
      },
      {
        "75",
        "PARENTAL_RATING_DESCRIPTOR_75"
      },
      {
        "76",
        "PARENTAL_RATING_DESCRIPTOR_76"
      },
      {
        "77",
        "PARENTAL_RATING_DESCRIPTOR_77"
      },
      {
        "78",
        "PARENTAL_RATING_DESCRIPTOR_78"
      },
      {
        "79",
        "PARENTAL_RATING_DESCRIPTOR_79"
      },
      {
        "100",
        "PARENTAL_RATING_DESCRIPTOR_100"
      },
      {
        "101",
        "PARENTAL_RATING_DESCRIPTOR_101"
      },
      {
        "102",
        "PARENTAL_RATING_DESCRIPTOR_102"
      },
      {
        "103",
        "PARENTAL_RATING_DESCRIPTOR_103"
      },
      {
        "104",
        "PARENTAL_RATING_DESCRIPTOR_104"
      },
      {
        "105",
        "PARENTAL_RATING_DESCRIPTOR_105"
      },
      {
        "106",
        "PARENTAL_RATING_DESCRIPTOR_106"
      },
      {
        "107",
        "PARENTAL_RATING_DESCRIPTOR_107"
      },
      {
        "108",
        "PARENTAL_RATING_DESCRIPTOR_108"
      },
      {
        "109",
        "PARENTAL_RATING_DESCRIPTOR_109"
      },
      {
        "110",
        "PARENTAL_RATING_DESCRIPTOR_110"
      },
      {
        "2283",
        "PARENTAL_RATING_DESCRIPTOR_2283"
      },
      {
        "4000",
        "PARENTAL_RATING_DESCRIPTOR_4000"
      },
      {
        "4001",
        "PARENTAL_RATING_DESCRIPTOR_4001"
      },
      {
        "4002",
        "PARENTAL_RATING_DESCRIPTOR_4002"
      },
      {
        "4003",
        "PARENTAL_RATING_DESCRIPTOR_4003"
      },
      {
        "4004",
        "PARENTAL_RATING_DESCRIPTOR_4004"
      },
      {
        "4005",
        "PARENTAL_RATING_DESCRIPTOR_4005"
      },
      {
        "4006",
        "PARENTAL_RATING_DESCRIPTOR_4006"
      },
      {
        "4999",
        "PARENTAL_RATING_DESCRIPTOR_4999"
      },
      {
        "5000",
        "PARENTAL_RATING_DESCRIPTOR_5000"
      },
      {
        "5001",
        "PARENTAL_RATING_DESCRIPTOR_5001"
      },
      {
        "5002",
        "PARENTAL_RATING_DESCRIPTOR_5002"
      },
      {
        "5003",
        "PARENTAL_RATING_DESCRIPTOR_5003"
      },
      {
        "5004",
        "PARENTAL_RATING_DESCRIPTOR_5004"
      },
      {
        "5005",
        "PARENTAL_RATING_DESCRIPTOR_5005"
      },
      {
        "5006",
        "PARENTAL_RATING_DESCRIPTOR_5006"
      },
      {
        "6000",
        "PARENTAL_RATING_DESCRIPTOR_6000"
      },
      {
        "6001",
        "PARENTAL_RATING_DESCRIPTOR_6001"
      },
      {
        "6002",
        "PARENTAL_RATING_DESCRIPTOR_6002"
      },
      {
        "6003",
        "PARENTAL_RATING_DESCRIPTOR_6003"
      },
      {
        "6004",
        "PARENTAL_RATING_DESCRIPTOR_6004"
      },
      {
        "6005",
        "PARENTAL_RATING_DESCRIPTOR_6005"
      },
      {
        "6006",
        "PARENTAL_RATING_DESCRIPTOR_6006"
      },
      {
        "10001",
        "PARENTAL_RATING_DESCRIPTOR_10001"
      },
      {
        "10002",
        "PARENTAL_RATING_DESCRIPTOR_10002"
      },
      {
        "10003",
        "PARENTAL_RATING_DESCRIPTOR_10003"
      },
      {
        "10004",
        "PARENTAL_RATING_DESCRIPTOR_10004"
      },
      {
        "10005",
        "PARENTAL_RATING_DESCRIPTOR_10005"
      },
      {
        "10006",
        "PARENTAL_RATING_DESCRIPTOR_10006"
      },
      {
        "10007",
        "PARENTAL_RATING_DESCRIPTOR_10007"
      },
      {
        "10008",
        "PARENTAL_RATING_DESCRIPTOR_10008"
      },
      {
        "10009",
        "PARENTAL_RATING_DESCRIPTOR_10009"
      },
      {
        "10010",
        "PARENTAL_RATING_DESCRIPTOR_10010"
      },
      {
        "14000",
        "PARENTAL_RATING_DESCRIPTOR_14000"
      },
      {
        "14001",
        "PARENTAL_RATING_DESCRIPTOR_14001"
      },
      {
        "14002",
        "PARENTAL_RATING_DESCRIPTOR_14002"
      },
      {
        "14003",
        "PARENTAL_RATING_DESCRIPTOR_14003"
      },
      {
        "14004",
        "PARENTAL_RATING_DESCRIPTOR_14004"
      },
      {
        "14005",
        "PARENTAL_RATING_DESCRIPTOR_14005"
      },
      {
        "14006",
        "PARENTAL_RATING_DESCRIPTOR_14006"
      },
      {
        "320010",
        "PARENTAL_RATING_DESCRIPTOR_320010"
      },
      {
        "320020",
        "PARENTAL_RATING_DESCRIPTOR_320020"
      },
      {
        "320030",
        "PARENTAL_RATING_DESCRIPTOR_320030"
      },
      {
        "320040",
        "PARENTAL_RATING_DESCRIPTOR_320040"
      },
      {
        "320050",
        "PARENTAL_RATING_DESCRIPTOR_320050"
      },
      {
        "320060",
        "PARENTAL_RATING_DESCRIPTOR_320060"
      }
    };

    public static string GetMovieRatingString(
      string ratingSystem,
      string rating,
      CultureInfo culture)
    {
      if (string.Equals("Unrated", rating, StringComparison.OrdinalIgnoreCase))
        return RatingStrings.ResourceManager.GetString("PARENTAL_UNRATED", culture);
      if (!string.IsNullOrEmpty(ratingSystem) && !string.IsNullOrEmpty(rating))
      {
        string name = string.Format((IFormatProvider) CultureInfo.InvariantCulture, "PARENTAL_RATING_{0}_{1}", new object[2]
        {
          (object) ratingSystem,
          (object) rating
        });
        if (!string.IsNullOrEmpty(name))
          return RatingStrings.ResourceManager.GetString(name, culture);
      }
      return string.Empty;
    }

    public static string GetTVRatingString(string ratingSystem, string rating, CultureInfo culture)
    {
      if (string.Equals("Unrated", rating, StringComparison.OrdinalIgnoreCase))
        return RatingStrings.ResourceManager.GetString("PARENTAL_UNRATED", culture);
      if (!string.IsNullOrEmpty(ratingSystem) && !string.IsNullOrEmpty(rating))
      {
        string name = string.Format((IFormatProvider) CultureInfo.InvariantCulture, "PARENTAL_RATING_{0}{1}_{2}", new object[3]
        {
          (object) RegionInfo.CurrentRegion.Name,
          (object) ratingSystem,
          (object) rating
        });
        if (!string.IsNullOrEmpty(name))
          return RatingStrings.ResourceManager.GetString(name, culture);
      }
      return string.Empty;
    }

    public static string GetGameRatingString(string ratingLevel, CultureInfo culture)
    {
      if (string.Equals("Unrated", ratingLevel, StringComparison.OrdinalIgnoreCase))
        return RatingStrings.ResourceManager.GetString("PARENTAL_UNRATED", culture);
      return !string.IsNullOrEmpty(ratingLevel) && RatingStringsHelper.liveRatingLevel.ContainsKey(ratingLevel) ? RatingStrings.ResourceManager.GetString(RatingStringsHelper.liveRatingLevel[ratingLevel], culture) : string.Empty;
    }

    public static string GetGameRatingDescriptor(string ratingDescriptor, CultureInfo culture)
    {
      return !string.IsNullOrEmpty(ratingDescriptor) && RatingStringsHelper.liveRatingDescriptor.ContainsKey(ratingDescriptor) ? RatingStrings.ResourceManager.GetString(RatingStringsHelper.liveRatingDescriptor[ratingDescriptor], culture) : string.Empty;
    }
  }
}
